In [1]:
#coding UTF-8

import numpy as np
import matplotlib.pylab as plt



In [2]:
#シグモイド関数
def sigmoid(x):
    return 1/(1+np.exp(-x))#配列を計算式にぶち込んでも、結果はちゃんと配列の要素ごとに計算した結果の配列が返される



In [9]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 

    x = x - np.max(x) # オーバーフロー対策
    return np.exp(x) / np.sum(np.exp(x))



In [10]:
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    # layer 初期設定
    W1=network['W1']
    b1=network['b1']
    W2=network['W2']
    b2=network['b2']
    W3=network['W3']
    b3=network['b3']
               
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2 layer3を実装してみてください
    a2=np.dot(z1, W2) + b2
    z2=sigmoid(a2)
    #layer3
    a3=np.dot(z2, W3) + b3
    z3 = sigmoid(a3)
    y = z3
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[ 0.57855079  0.66736228]]


In [13]:
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(x_batch)
    print(y_batch)#めっちゃ見づらかった


1000
[[  5.68925209e-01   4.57827450e-01]
 [  5.55264889e-01   2.03445358e-01]
 [  1.31454757e-01   3.78977936e-01]
 [  6.79804011e-01   8.41321463e-01]
 [  3.66265034e-01   7.11501426e-01]
 [  4.47890419e-01   9.19320101e-01]
 [  7.96203427e-01   9.59831254e-01]
 [  2.13977068e-01   8.72999256e-04]
 [  4.30754483e-01   9.11175407e-01]
 [  2.26504515e-01   9.36943292e-01]
 [  5.45477678e-01   5.49808474e-01]
 [  1.73537601e-01   2.88931163e-01]
 [  6.30507807e-01   4.66117291e-01]
 [  4.70767489e-01   5.63932453e-01]
 [  3.91689226e-02   8.43988514e-01]
 [  1.88332894e-01   7.45947375e-01]]
[[ 0.57798443  0.66621438]
 [ 0.57754762  0.66533055]
 [ 0.5772899   0.66480671]
 [ 0.57869133  0.66764487]
 [ 0.57814094  0.66652991]
 [ 0.57854966  0.66735715]
 [ 0.5789763   0.66822175]
 [ 0.57672305  0.66366006]
 [ 0.57851862  0.66729427]
 [ 0.57832433  0.66690018]
 [ 0.57810197  0.66645204]
 [ 0.57718818  0.6646011 ]
 [ 0.57807241  0.66639271]
 [ 0.57803404  0.66631421]
 [ 0.57795409  0.6661501